<?php

require 'loader.php';

$alumnoNuevo=new Alumno("Lucia", "Cavagna",123456);
$alumnoNuevo2=new Alumno("Facundo","Fierro",789123);
$alumnoNuevo3=new Alumno("Michelle","Boudakian",741258);
$alumnoNuevo4=new Alumno("Braian Leonel","Mastrogiacomo",963258);
$alumnoNuevo5=new Alumno("Gaston","Belio", 471258); 
var_dump($alumnoNuevo);
echo "<br>";
var_dump($alumnoNuevo2);
echo "<br>";
echo "<hr>";
echo "<br>";
//  **echo "<b> HOLITAS </b>";
//  **$cursoNuevo=new Curso("TN02",10);
//  **var_dump($cursoNuevo);
//  **echo "<br>";
//  **echo "<hr>";
//  **echo "<br>";
//$profeNuevo=new Profesor("Daniel","Fuentes",123,18);
//var_dump($profeNuevo);
//echo "<br>";
//echo "<hr>";
//echo "<br>";
$profett=new ProfesorTitular("Daniel","Fuentes",123,"php");
$profett->setNombre("Danielito");
echo "VarDump de get";
echo "<br>";
var_dump($profett->getNombre());
echo "<br>";
echo "<hr>";
echo "<br>";
var_dump($profett);
echo "<br>";
echo "<hr>";
echo "<br>";
$profeAdj=new ProfesorAdjunto("Hernan","Baravalle",99,5);
var_dump($profeAdj);
echo "<br>";
echo "<hr>";
echo "<br>";
$profeAdj->setHoras(3);
$profeAdj->SetApellido("Baravallecito"); 
var_dump($profeAdj);
echo "<br>";
echo "<hr>";
echo "<br>";
$cursoNuevo=new Curso("TNSpecial", 1235, 6);
$cursoNuevo2=new Curso("TNViernes", 4569, 9);
$cursoNuevo3=new Curso("TNEterno", 5826, 4);
var_dump($cursoNuevo);
echo "<br>";
echo "<hr>";
echo "<br>";
$cursoNuevo->setAlumnos($alumnoNuevo);
$cursoNuevo->setAlumnos($alumnoNuevo2);
$cursoNuevo->setAlumnos($alumnoNuevo3);
$cursoNuevo->setAlumnos($alumnoNuevo4);
var_dump($cursoNuevo->listar());
echo "<br>";
echo "<hr>";
echo "<br>";
/* var_dump($cursoNuevo->Profesores());
echo "<br>";
echo "<hr>";
echo "<br>"; */
var_dump($cursoNuevo->agregarUnAlumno($alumnoNuevo5));
echo "<br>";
echo "<hr>";
echo "<br>";
var_dump($cursoNuevo->listar());
echo "<br>";
echo "<hr>";
echo "<br>";
$DHManager=new DigitalHouseManager();
/* $DHManager->altacurso($cursoNuevo);
$DHManager->altacurso($cursoNuevo2);
$DHManager->altacurso($cursoNuevo3);
dump($DHManager); */
$DHManager->altaCurso("TNSpecial",145236,40);
dump($DHManager);
echo "<br>";
echo "<hr>";
echo "<br>";
$DHManager->altaProfesorAdj("Ignacio","Vuotto",50,3);
$DHManager->setListaProfesores($DHManager->listaProfesores[0],0);
dump($DHManager);
echo "<br>";
echo "<hr>";
echo "<br>";
$DHManager->altaProfesorAdj("Hernan", "Baravalle", 20,3);
$DHManager->setListaProfesores($DHManager->listaProfesores[1],5);
dump($DHManager);
